default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: experimental_api_development
test:
  <<: *default
  database: experimental_api_test
production:
  url: <%= ENV["EXPERIMENTAL_DB"] %>
