name: "Ruby on Rails CI"
on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

permissions:
  packages: write
  contents: read

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Install Ruby and gems
        uses: ruby/setup-ruby@55283cc23133118229fd3f97f9336ee23a179fcf # v1.146.0
        with:
          bundler-cache: true
      - name: Lint Ruby files
        run: bundle exec rubocop --parallel
  test:
    runs-on: ubuntu-latest
    services:
      postgres:
        image: postgres:11-alpine
        ports:
          - "5432:5432"
        env:
          POSTGRES_DB: rails_test
          POSTGRES_USER: rails
          POSTGRES_PASSWORD: password
    env:
      RAILS_ENV: test
      DB_USERNAME: rails
      DB_PASSWORD: password
      DB_HOST: localhost
      CI_ENV: github-actions
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      # Add or replace dependency steps here
      - name: Install Ruby and gems
        uses: ruby/setup-ruby@55283cc23133118229fd3f97f9336ee23a179fcf # v1.146.0
        with:
          bundler-cache: true
      - name: Set up database schema
        run: |
          bundle exec rails db:prepare
          bundle exec rails parallel:create
          bundle exec rails parallel:prepare
      - name: Run tests
        run: bundle exec rails parallel:spec
  build_and_deploy:
    needs: [ lint, test ]
    runs-on: ubuntu-latest
    if: github.event_name == 'push' && github.ref == 'refs/heads/main'
    steps:
      - uses: actions/checkout@v3
      - name: Log in to GitHub Docker Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Build and push Docker image
        run: |
          time=$(date +%s)
          docker build . --file Dockerfile --tag ghcr.io/${{ github.repository }}/experiments_api:$time
          docker push ghcr.io/${{ github.repository }}/experiments_api:$time
          docker tag ghcr.io/${{ github.repository }}/experiments_api:$time ghcr.io/${{ github.repository }}/experiments_api:latest
          docker push ghcr.io/${{ github.repository }}/experiments_api:latest
